# Generated by Django 5.0 on 2023-12-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=24)),
                ("volume", models.CharField(max_length=512)),
                ("trade_price", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
